/* Generated by Edge v.0.0.1 */
(function() {
  var graph = new Graph2D(document.getElementById('edgecanvas'));
  graph.setOption('applyGravity', false);

  /* Create nodes */
  var A = graph.createNode({renderData: {name: 'a'}});
  var B = graph.createNode({renderData: {name: '_'}});
  var C = graph.createNode({renderData: {name: '_'}});

  /* Create edges */
  graph.linkNodes(A, B);
  graph.linkNodes(A, C);
  graph.linkNodes(B, C);
})();
