/* Generated by Edge v.0.0.1 */
(function() {
  var graph = new Graph2D(document.getElementById('edgecanvas'));
  graph.setOption('applyGravity', false);

  /* Create nodes */
  var A = graph.createNode({renderData: {name: 'A'}});
  var B = graph.createNode({renderData: {name: 'B'}});
  var C = graph.createNode({renderData: {name: 'C'}});

  /* Create edges */
  graph.linkNodes(A, B, { $directedTowards: B });
  graph.linkNodes(A, C, { $directedTowards: C });
  graph.linkNodes(B, C, { $directedTowards: C });
})();